language: python
env:
  - TEST_SUITE=unit
  - TEST_SUITE=journey
python: 3.5
install:
  - python setup.py develop
  - pip install coveralls
script: coverage run -m unittest discover tests/$TEST_SUITE
after_success: coveralls
