language: python
python: 3.5
cache:
  directories:
    - $HOME/virtualenv/python3.5.3/
jobs:
  include:
    - stage: unit
      script: coverage run -m unittest discover tests/unit
    - stage: journey
      script: coverage run -m unittest discover tests/journey
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: serenata
        password: $PYPI_PASSWORD
        distributions: "sdist bdist_wheel"
        on:
          branch: master
install:
  - python setup.py develop
  - pip install coveralls

after_success: coveralls
